module.exports = {
  apps: [
    {
      name: 'camera-bridge',
      script: 'server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'camera-bridge-control',
      script: 'control-server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        CONTROL_PORT: '3003',
        CAMERA_BRIDGE_CONTROL_TOKEN: process.env.CAMERA_BRIDGE_CONTROL_TOKEN || 'change-me-in-production',
      },
      error_file: './logs/control-err.log',
      out_file: './logs/control-out.log',
      log_file: './logs/control-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'video-stream-server',
      script: 'video-stream-server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        VIDEO_STREAM_PORT: process.env.VIDEO_STREAM_PORT || '3004',
        CAMERA_1_IP: process.env.CAMERA_1_IP || '192.168.1.50',
        CAMERA_1_PORT: process.env.CAMERA_1_PORT || '8000',
        CAMERA_1_USERNAME: process.env.CAMERA_1_USERNAME || 'admin',
        CAMERA_1_PASSWORD: process.env.CAMERA_1_PASSWORD || 'admin',
        CAMERA_2_IP: process.env.CAMERA_2_IP || '192.168.1.49',
        CAMERA_2_PORT: process.env.CAMERA_2_PORT || '8000',
        CAMERA_2_USERNAME: process.env.CAMERA_2_USERNAME || 'admin',
        CAMERA_2_PASSWORD: process.env.CAMERA_2_PASSWORD || 'admin',
      },
      error_file: './logs/video-err.log',
      out_file: './logs/video-out.log',
      log_file: './logs/video-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
};

